services:
  community-webserver:
    image: public.ecr.aws/a3y4e2t5/ktb-community/webserver-registry:latest
    container_name: community-webserver
    restart: unless-stopped
    networks: 
      - community-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro

networks:
  community-network:
    external: true
    name: community-network