services:
  webserver-nginx:
    image: public.ecr.aws/a3y4e2t5/ktb-community/fe-registry:latest
    container_name: community-webserver-nginx
    restart: unless-stopped
    networks: 
      - community-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro

volumes:
  nginx_html:
    driver: local

networks:
  community-network:
    driver: bridge